--CREATE DATABASE Spotify
--USE Spotify


--CREATE TABLE USERS(
--ID INT PRIMARY KEY IDENTITY,
--NAME NVARCHAR(50) NOT NULL,
--SURNAME NVARCHAR(50) DEFAULT 'XXX',
--USERNAME NVARCHAR(50) NOT NULL UNIQUE,
--PASSWORD INT CHECK(PASSWORD>=8),
--GENDER NVARCHAR(50) NOT NULL
--)


--CREATE TABLE ARTISTS(
--ID INT PRIMARY KEY IDENTITY,
--NAME NVARCHAR(50) NOT NULL,
--SURNAME NVARCHAR(50) NOT NULL UNIQUE,
--BIRHIDAY DATETIME NOT NULL,
--GENDER NVARCHAR(50) NOT NULL
--)


--CREATE TABLE CATEGORIES(
--ID INT PRIMARY KEY IDENTITY,
--NAME NVARCHAR(50) NOT NULL
--)


CREATE TABLE MUSICS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
DURATION TIME NOT NULL,
CATEGORIEID INT REFERENCES CATEGORIES(ID),
ARTISTID INT REFERENCES ARTISTS(ID)
)




--CREATE TABLE PLAYLISTS(
--ID INT PRIMARY KEY IDENTITY,
--NAME NVARCHAR(50) NOT NULL,
--USERID INT REFERENCES USERS(ID),
--MUSICID INT REFERENCES MUSICS(ID)
--)



--INSERT INTO USERS VALUES('NURLAN','ABBASOV','ABBANUR',123456789,'KISI'),('USER2','USER2OV','USERU',987654321,'KISI')
--INSERT INTO ARTISTS VALUES('Ed','Sheeran','1991','KISI'),('Justin ','Bieber','1994','KISI')
--INSERT INTO CATEGORIES VALUES('POP'),('KLASIK')
INSERT INTO MUSICS VALUES('Shape of You','3:53',1,1),
('Sorry','3:20',1,2),
('Baby','3.34',2,2)
INSERT INTO PLAYLISTS VALUES('NUSpotify', 1, 1),('NUSpotify', 1, 2),('USER2Spotify', 2, 3)

--SELECT * FROM USERS
--SELECT * FROM ARTISTS
--SELECT * FROM CATEGORIES
SELECT * FROM MUSICS
SELECT * FROM PLAYLISTS



-----SORGU 1
CREATE VIEW VW_GETMUSICSNAMEWIHT...
AS
SELECT M.NAME AS MUSICNAME, M.DURATION, C.NAME AS CATEGORIE, CONCAT(A.NAME, ' ', A.SURNAME) AS ARTIST
FROM MUSICS AS M
JOIN CATEGORIES AS C 
ON M.CATEGORIEID = C.ID
JOIN ARTISTS AS A
ON M.ARTISTID = A.ID;


-----SORGU 2

SELECT M.NAME AS MUSICNAME
FROM MUSICS AS M
JOIN PLAYLISTS AS P 
ON PLAYLISTID = P.PLAYLISTID
JOIN USERS AS U 
ON P.USERID = U.USERID
WHERE U.USERNAME= 'ABBANUR'


-----SORGU 3
SELECT NAME AS MUSICNAME, DURATION
FROM MUSICS
ORDER BY DURATION;

-----SORGU 4
